# docker-compose.yml
version: "3.9"
services:
  db:
    container_name: RORO_BLOGS
    image: postgres:17-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=RORO_BLOG_BACKEND
volumes:
  postgres-data: